apiVersion: v1
kind: BuildConfig
metadata:
  name: mavenpipeline
  labels:
    name: mavenpipeline
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "maven", "namespace": "", "kind": "DeploymentConfig"}]'
spec:
  triggers:
    -
      type: GitHub
      github:
        secret: secret101
    -
      type: Generic
      generic:
        secret: secret101
  runPolicy: Serial
  source:
    type: None
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: "node('maven'){\nstage 'Checkout'\ngit url: 'https://github.com/petenorth/spring-boot-cxf-jaxrs.git'\nwithMaven(\nmaven: 'M3') {\nsh "mvn clean install"\n}\n}"
  output:
  resources:
  postCommit:
status:
  lastVersion: 1
