apiVersion: v1
kind: BuildConfig
metadata:
  name: mavenpipeline
  labels:
    name: mavenpipeline
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "maven", "namespace": "", "kind": "DeploymentConfig"}]'
spec:
  triggers:
    -
      type: GitHub
      github:
        secret: secret101
    -
      type: Generic
      generic:
        secret: secret101
  runPolicy: Serial
  source:
    type: None
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: "node{\n// Mark the code checkout 'stage'....\nstage 'Checkout'\n\n// Get some code from a GitHub repository\ngit url: 'https://github.com/petenorth/spring-boot-cxf-jaxrs.git'\n\n// Mark the code build\nstage 'Build'\n\nwithMaven(\nmaven: 'M3') { \n//mavenSettingsConfig: 'maven-settings-for-gameoflife', \n//mavenLocalRepo: '.repository') {\n\n// Run the maven build\nsh "mvn clean install"\n}\n}"
  output:
  resources:
  postCommit:
status:
  lastVersion: 1
