apiVersion: v1
kind: BuildConfig
metadata:
  name: jaxrspipeline
  labels:
    name: jaxrspipeline
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "jaxrs", "namespace": "", "kind": "DeploymentConfig"}]'
spec:
  triggers:
    -
      type: GitHub
      github:
        secret: secret101
    -
      type: Generic
      generic:
        secret: secret101
  runPolicy: Serial
  source:
    type: None
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: "node('maven') {\nstage 'buildInDevelopment'\nopenshiftBuild(namespace: 'spring-boot-cxf-jaxrs', buildConfig: 's2i-springboot-cxf-jaxrs', showBuildLogs: 'true')\nstage 'deployInDevelopment'\nopenshiftDeploy(namespace: 'spring-boot-cxf-jaxrs', deploymentConfig: 's2i-springboot-cxf-jaxrs')\nopenshiftScale(namespace: 'spring-boot-cxf-jaxrs', deploymentConfig: 's2i-springboot-cxf-jaxrs',replicaCount: '1')\n}"
  output:
  resources:
  postCommit:
status:
  lastVersion: 1
